// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class tbCargos
    {
        public tbCargos()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int carg_Id { get; set; }
        public string carg_Descripcion { get; set; }
        public DateTime carg_FechaCreacion { get; set; }
        public int carg_UsuarioCreacion { get; set; }
        public DateTime? carg_FechaModificacion { get; set; }
        public int? carg_UsuarioModificacion { get; set; }
        public bool? carg_Estado { get; set; }

        public virtual tbUsuarios carg_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios carg_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}