// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class tbClientes
    {
        public tbClientes()
        {
            tbFacturas = new HashSet<tbFacturas>();
            tbReservaciones = new HashSet<tbReservaciones>();
        }

        public int clie_Id { get; set; }
        public string clie_Nombre { get; set; }
        public string clie_Apellido { get; set; }
        public string clie_Telefono { get; set; }
        public string clie_CorreoElectronico { get; set; }
        public DateTime clie_FechaCreacion { get; set; }
        public int clie_UsuarioCreacion { get; set; }
        public DateTime? clie_FechaModificacion { get; set; }
        public int? clie_UsuarioModificacion { get; set; }
        public bool? clie_Estado { get; set; }

        public virtual tbUsuarios clie_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios clie_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
        public virtual ICollection<tbReservaciones> tbReservaciones { get; set; }
    }
}