// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int estc_Id { get; set; }
        public string estc_Descripcion { get; set; }
        public DateTime estc_FechaCreacion { get; set; }
        public int estc_UsuarioCreacion { get; set; }
        public DateTime? estc_FechaModificacion { get; set; }
        public int? estc_UsuarioModificacion { get; set; }
        public bool? estc_Estado { get; set; }

        public virtual tbUsuarios estc_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios estc_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}