// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class tbFacturas
    {
        public tbFacturas()
        {
            tbFacturasDetalles = new HashSet<tbFacturasDetalles>();
        }

        public int fact_Id { get; set; }
        public int clie_Id { get; set; }
        public int empl_Id_Atendido { get; set; }
        public int empl_Id_Caja { get; set; }
        public int metp_Id { get; set; }
        public DateTime fact_Fecha { get; set; }
        public DateTime fact_FechaCreacion { get; set; }
        public int fact_UsuarioCreacion { get; set; }
        public DateTime? fact_FechaModificacion { get; set; }
        public int? fact_UsuarioModificacion { get; set; }
        public bool? fact_Estado { get; set; }

        public virtual tbClientes clie { get; set; }
        public virtual tbEmpleados empl_Id_AtendidoNavigation { get; set; }
        public virtual tbEmpleados empl_Id_CajaNavigation { get; set; }
        public virtual tbUsuarios fact_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios fact_UsuarioModificacionNavigation { get; set; }
        public virtual tbMetodoPago metp { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetalles { get; set; }
    }
}