// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class tbFacturasDetalles
    {
        public int fade_Id { get; set; }
        public int fact_Id { get; set; }
        public int? prod_Id { get; set; }
        public int? serv_Id { get; set; }
        public int fade_Cantidad { get; set; }
        public decimal fade_Precio { get; set; }
        public DateTime fade_FechaCreacion { get; set; }
        public int fade_UsuarioCreacion { get; set; }
        public DateTime? fade_FechaModificacion { get; set; }
        public int? fade_UsuarioModificacion { get; set; }
        public bool? fade_Estado { get; set; }

        public virtual tbFacturas fact { get; set; }
        public virtual tbUsuarios fade_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios fade_UsuarioModificacionNavigation { get; set; }
        public virtual tbProductos prod { get; set; }
        public virtual tbServicios serv { get; set; }
    }
}