// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class tbMetodoPago
    {
        public tbMetodoPago()
        {
            tbFacturas = new HashSet<tbFacturas>();
        }

        public int metp_Id { get; set; }
        public string metp_Descripcion { get; set; }
        public DateTime metp_FechaCreacion { get; set; }
        public int metp_UsuarioCreacion { get; set; }
        public DateTime? metp_FechaModificacion { get; set; }
        public int? metp_UsuarioModificacion { get; set; }
        public bool? metp_Estado { get; set; }

        public virtual tbUsuarios metp_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios metp_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
    }
}