// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class tbProductosXServicio
    {
        public int spro_Id { get; set; }
        public int? serv_Id { get; set; }
        public int? prod_Id { get; set; }
        public DateTime spro_FechaCreacion { get; set; }
        public int spro_UsuarioCreacion { get; set; }
        public DateTime? spro_FechaModificacion { get; set; }
        public int? spro_UsuarioModificacion { get; set; }
        public bool? spro_Estado { get; set; }

        public virtual tbProductos prod { get; set; }
        public virtual tbServicios serv { get; set; }
        public virtual tbUsuarios spro_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios spro_UsuarioModificacionNavigation { get; set; }
    }
}