// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class tbServicios
    {
        public tbServicios()
        {
            tbFacturasDetalles = new HashSet<tbFacturasDetalles>();
            tbProductosXServicio = new HashSet<tbProductosXServicio>();
        }

        public int serv_Id { get; set; }
        public string serv_Nombre { get; set; }
        public string serv_Descripcion { get; set; }
        public decimal serv_Precio { get; set; }
        public DateTime serv_FechaCreacion { get; set; }
        public int serv_UsuarioCreacion { get; set; }
        public DateTime? serv_FechaModificacion { get; set; }
        public int? serv_UsuarioModificacion { get; set; }
        public bool? serv_Estado { get; set; }

        public virtual tbUsuarios serv_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios serv_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetalles { get; set; }
        public virtual ICollection<tbProductosXServicio> tbProductosXServicio { get; set; }
    }
}