// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SalonDeBellezaCarlitos.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseusur_UsuarioCreacionNavigation = new HashSet<tbUsuarios>();
            Inverseusur_UsuarioModificacionNavigation = new HashSet<tbUsuarios>();
            tbCargoscarg_UsuarioCreacionNavigation = new HashSet<tbCargos>();
            tbCargoscarg_UsuarioModificacionNavigation = new HashSet<tbCargos>();
            tbCategoriascate_UsuarioCreacionNavigation = new HashSet<tbCategorias>();
            tbCategoriascate_UsuarioModificacionNavigation = new HashSet<tbCategorias>();
            tbClientesclie_UsuarioCreacionNavigation = new HashSet<tbClientes>();
            tbClientesclie_UsuarioModificacionNavigation = new HashSet<tbClientes>();
            tbDepartamentosdepa_UsuarioCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdepa_UsuarioModificacionNavigation = new HashSet<tbDepartamentos>();
            tbEmpleadosempl_UsuarioCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosempl_UsuarioModificacionNavigation = new HashSet<tbEmpleados>();
            tbEstadosCivilesestc_UsuarioCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesestc_UsuarioModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbFacturasDetallesfade_UsuarioCreacionNavigation = new HashSet<tbFacturasDetalles>();
            tbFacturasDetallesfade_UsuarioModificacionNavigation = new HashSet<tbFacturasDetalles>();
            tbFacturasfact_UsuarioCreacionNavigation = new HashSet<tbFacturas>();
            tbFacturasfact_UsuarioModificacionNavigation = new HashSet<tbFacturas>();
            tbMetodoPagometp_UsuarioCreacionNavigation = new HashSet<tbMetodoPago>();
            tbMetodoPagometp_UsuarioModificacionNavigation = new HashSet<tbMetodoPago>();
            tbMunicipiosmuni_UsuarioCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmuni_UsuarioModificacionNavigation = new HashSet<tbMunicipios>();
            tbProductosXServiciospro_UsuarioCreacionNavigation = new HashSet<tbProductosXServicio>();
            tbProductosXServiciospro_UsuarioModificacionNavigation = new HashSet<tbProductosXServicio>();
            tbProductosprod_UsuarioCreacionNavigation = new HashSet<tbProductos>();
            tbProductosprod_UsuarioModificacionNavigation = new HashSet<tbProductos>();
            tbReservacionesrese_UsuarioCreacionNavigation = new HashSet<tbReservaciones>();
            tbReservacionesrese_UsuarioModificacionNavigation = new HashSet<tbReservaciones>();
            tbServiciosserv_UsuarioCreacionNavigation = new HashSet<tbServicios>();
            tbServiciosserv_UsuarioModificacionNavigation = new HashSet<tbServicios>();
            tbSucursalessucu_UsuarioCreacionNavigation = new HashSet<tbSucursales>();
            tbSucursalessucu_UsuarioModificacionNavigation = new HashSet<tbSucursales>();
        }

        public int usur_Id { get; set; }
        public string usur_Usuario { get; set; }
        public string usur_Contrasenia { get; set; }
        public int empl_Id { get; set; }
        public int usur_UsuarioCreacion { get; set; }
        public DateTime usur_FechaCreacion { get; set; }
        public int? usur_UsuarioModificacion { get; set; }
        public DateTime? usur_FechaModificacion { get; set; }
        public bool? usur_Estado { get; set; }

        public virtual tbEmpleados empl { get; set; }
        public virtual tbUsuarios usur_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usur_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusur_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusur_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriascate_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriascate_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestc_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestc_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetallesfade_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetallesfade_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfact_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfact_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbMetodoPago> tbMetodoPagometp_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbMetodoPago> tbMetodoPagometp_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbProductosXServicio> tbProductosXServiciospro_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbProductosXServicio> tbProductosXServiciospro_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductosprod_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductosprod_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbReservaciones> tbReservacionesrese_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbReservaciones> tbReservacionesrese_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbServicios> tbServiciosserv_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbServicios> tbServiciosserv_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UsuarioModificacionNavigation { get; set; }
    }
}